apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: jenkins
  name: jenkins
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "create","delete", "update","list","watch"]
  resources: ["configmaps"]
  verbs: ["get","list","patch","watch"]
  resources: ["persistentvolumeclaims"]
  verbs: ["get","list","update","create","delete","watch"]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  apiGroup: ""
roleRef:
  kind: Role
  name: jenkins
  apiGroup: ""
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: '8.0.x'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
    global.storageClass: gp2
    jenkinsUser: admin
    jenkinsPassword: obmedia2022 
